version: "3.8"

services:
    dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:dockercheck
    restart: unless-stopped
    build: .
    environment:
        - APP_ENV=development
        - APP_PORT=8080
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
  
networks:
  default:
    external:
      name: app